# #Task 1: Get familier with the data
#Import the necessary libraries
#Read yelp.csv into a pandas DataFrame and examine it

In [134]:
#Python libraries for exploring and manipulating data
import pandas as pd
import numpy as np
#import pandas_profiling

In [135]:
# read a dataset of nfl into a DataFrame
nfl = pd.read_csv('/Users/ketansahu/Downloads/Machine Learning Practice/NFL Play by Play 2009-2017 (v4).csv')
# examine the first 5 rows of the yelp data
nfl.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

In [136]:
# Examine the shape of the data set
print(nfl.shape)

(407688, 102)

In [137]:
# Examine the data type
print(nfl.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407688 entries, 0 to 407687
Columns: 102 entries, Date to Season
dtypes: float64(33), int64(31), object(38)
memory usage: 317.3+ MB
None

In [138]:
# Examine the data type of all the columns entry
nfl.dtypes

Date                            object
GameID                           int64
Drive                            int64
qtr                              int64
down                           float64
time                            object
TimeUnder                        int64
TimeSecs                       float64
PlayTimeDiff                   float64
SideofField                     object
yrdln                          float64
yrdline100                     float64
ydstogo                          int64
ydsnet                           int64
GoalToGo                       float64
FirstDown                      float64
posteam                         object
DefensiveTeam                   object
desc                            object
PlayAttempted                    int64
Yards.Gained                     int64
sp                               int64
Touchdown                        int64
ExPointResult                   object
TwoPointConv                    object
DefTwoPoint                     object
Safety                           int64
Onsidekick                       int64
PuntResult                      object
PlayType                        object
                                ...
AwayTeam                        object
Timeout_Indicator                int64
Timeout_Team                    object
posteam_timeouts_pre             int64
HomeTimeouts_Remaining_Pre       int64
AwayTimeouts_Remaining_Pre       int64
HomeTimeouts_Remaining_Post      int64
AwayTimeouts_Remaining_Post      int64
No_Score_Prob                  float64
Opp_Field_Goal_Prob            float64
Opp_Safety_Prob                float64
Opp_Touchdown_Prob             float64
Field_Goal_Prob                float64
Safety_Prob                    float64
Touchdown_Prob                 float64
ExPoint_Prob                   float64
TwoPoint_Prob                  float64
ExpPts                         float64
EPA                            float64
airEPA                         float64
yacEPA                         float64
Home_WP_pre                    float64
Away_WP_pre                    float64
Home_WP_post                   float64
Away_WP_post                   float64
Win_Prob                       float64
WPA                            float64
airWPA                         float64
yacWPA                         float64
Season                           int64
Length: 102, dtype: object

In [139]:
#Examine the summary statistics of only integers of nfl dataframe
nfl.describe(include='int')

,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,Touchdown,...,Challenge.Replay,Accepted.Penalty,Penalty.Yards,Timeout_Indicator,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,Season
count,4.076880e+05,407688.000000,407688.000000,407688.000000,407688.000000,407688.000000,407688.0,407688.000000,407688.000000,407688.000000,...,407688.000000,407688.000000,407688.000000,407688.000000,407688.000000,407688.000000,407688.000000,407688.000000,407688.000000,407688.000000
mean,2.013158e+09,12.316158,2.577412,7.374200,7.309403,25.945517,1.0,4.994221,0.071844,0.029069,...,0.008372,0.072357,0.613673,0.041215,2.521239,2.540479,2.517222,2.520118,2.496367,2013.018985
std,2.572839e+06,7.149527,1.129750,4.642388,4.869987,24.862079,0.0,9.102092,0.258230,0.168000,...,0.091113,0.259078,2.621540,0.198788,0.778066,0.760419,0.778348,0.780151,0.797917,2.576962
min,2.009091e+09,1.000000,1.000000,0.000000,0.000000,-87.000000,1.0,-74.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,-3.000000,-1.000000,-3.000000,-1.000000,2009.000000
25%,2.011101e+09,6.000000,2.000000,3.000000,3.000000,5.000000,1.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2011.000000
50%,2.013111e+09,12.000000,3.000000,7.000000,9.000000,19.000000,1.0,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,2013.000000
75%,2.015121e+09,18.000000,4.000000,11.000000,10.000000,43.000000,1.0,7.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,2015.000000
max,2.017123e+09,35.000000,5.000000,15.000000,50.000000,99.000000,1.0,99.000000,1.000000,1.000000,...,1.000000,1.000000,66.000000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,2017.000000

In [140]:
#Examine the summary statistics of only floats of nfl dataframe
nfl.describe(include='float')

,down,TimeSecs,PlayTimeDiff,yrdln,yrdline100,GoalToGo,FirstDown,FieldGoalDistance,PosTeamScore,DefTeamScore,...,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA
count,346534.000000,407464.000000,407244.000000,406848.000000,406848.000000,406848.000000,378877.000000,8948.000000,380784.000000,380784.000000,...,159294.000000,159190.000000,382734.000000,382734.000000,381101.000000,381101.000000,382679.000000,402147.000000,159187.000000,158926.000000
mean,2.002476,1695.268944,20.576762,28.488327,48.644081,0.049134,0.290509,37.465132,10.201424,11.414484,...,0.524818,-0.386086,0.534488,0.465965,0.534791,0.465613,0.501320,0.002099,0.015135,-0.010480
std,1.006353,1062.801012,17.969326,12.946471,25.070416,0.216148,0.453998,10.282682,9.432067,9.910753,...,1.394159,1.972715,0.285574,0.285629,0.287818,0.287867,0.287445,0.045363,0.056490,0.068139
min,1.000000,-900.000000,0.000000,1.000000,1.000000,0.000000,0.000000,18.000000,0.000000,0.000000,...,-12.849594,-14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.997214,-0.999881,-0.986673
25%,1.000000,778.000000,5.000000,20.000000,30.000000,0.000000,0.000000,29.000000,2.000000,3.000000,...,-0.502895,-0.961115,0.325123,0.231411,0.321701,0.227694,0.276472,-0.014728,-0.011518,-0.018683
50%,2.000000,1800.000000,17.000000,30.000000,49.000000,0.000000,0.000000,38.000000,7.000000,10.000000,...,0.295977,0.000000,0.531274,0.469052,0.533609,0.466670,0.504470,0.000000,0.003441,0.000000
75%,3.000000,2585.000000,37.000000,39.000000,70.000000,0.000000,1.000000,46.000000,16.000000,17.000000,...,1.386486,0.485508,0.769232,0.675530,0.772882,0.678833,0.725477,0.014684,0.035792,0.011431
max,4.000000,3600.000000,943.000000,50.000000,99.000000,1.000000,1.000000,71.000000,61.000000,61.000000,...,7.346969,9.559834,1.000000,1.000000,1.000000,1.000000,1.000000,0.994848,0.994848,1.000000

In [141]:
#Examine the summary statistics of only objects of nfl dataframe
nfl.describe(include='object')

,Date,time,SideofField,posteam,DefensiveTeam,desc,ExPointResult,TwoPointConv,DefTwoPoint,PuntResult,...,FieldGoalResult,RecFumbTeam,RecFumbPlayer,ChalReplayResult,PenalizedTeam,PenaltyType,PenalizedPlayer,HomeTeam,AwayTeam,Timeout_Team
count,407688,407464,407160,382696,382696,407686,10110,605,24,22371,...,9059,4373,4373,3402,29499,16427,28285,407688,407688,407688
unique,426,901,37,35,35,375962,4,2,2,2,...,3,34,1827,2,34,77,3357,35,35,36
top,2016-01-03,15:00,OAK,NE,PHI,Two-Minute Warning,Made,Failure,Failure,Clean,...,Good,CHI,M.Adams,Upheld,OAK,False Start,A.Smith,NE,PHI,None
freq,2872,11792,13270,12520,12321,3739,9850,322,19,22253,...,7582,165,15,1986,1159,5284,154,13165,13129,390885

# Task 2: Handling missing values
#how many missing data points, the dataset have

In [185]:
# 'isnull' returns a DataFrame of booleans (True if missing, False if not missing)
nfl.isnull().head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,True,False

In [186]:
#new alias for isnull
nfl.isna().head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,True,False

In [187]:
# 'notnull' returns the opposite of 'isnull' (True if not missing, False if missing)
nfl.notnull().head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,True,True,True,True,False,True,True,True,True,True,...,False,True,True,True,True,True,True,False,False,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,False,False,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,False,False,True

In [188]:
#new alias for notnull
nfl.notna().head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,True,True,True,True,False,True,True,True,True,True,...,False,True,True,True,True,True,True,False,False,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,False,False,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,False,False,True

In [183]:
# Get the number of missing data points per column
nfl_missing_values_sum_per_col = nfl.isnull().sum().sort_values(ascending= False)
print("Sum of missing values/column in nfl dataset",nfl_missing_values_sum_per_col.head())

print('_'*40)
nfl_values_count_per_col = nfl.isnull().count()
print("Total number(count) of values in nfl dataset", nfl_values_count_per_col.head())


nfl_missing_values_percentage_per_col = (nfl_missing_values_sum_per_col/nfl_values_count_per_col)*100
print('_'*40)

missing_data = pd.concat([nfl_missing_values_sum_per_col,nfl_missing_values_percentage_per_col],axis=1,keys=['Total', 'Percent'])
missing_data.sort_values("Percent",ascending= False).head(10)

('Sum of missing values/column in nfl dataset', DefTwoPoint         407664
BlockingPlayer      407571
TwoPointConv        407083
ChalReplayResult    404286
RecFumbTeam         403315
dtype: int64)
________________________________________
('Total number(count) of values in nfl dataset', Date      407688
GameID    407688
Drive     407688
qtr       407688
down      407688
dtype: int64)
________________________________________

                    Total    Percent
DefTwoPoint        407664  99.994113
BlockingPlayer     407571  99.971302
TwoPointConv       407083  99.851602
ChalReplayResult   404286  99.165538
RecFumbPlayer      403315  98.927366
RecFumbTeam        403315  98.927366
Interceptor        403168  98.891309
FieldGoalDistance  398740  97.805184
FieldGoalResult    398629  97.777958
ExPointResult      397578  97.520162

In [182]:
#we will first drop all the columns, which have missing values total more than 100
nfl_data = nfl.drop((missing_data[missing_data['Total'] > 100].index),1)
nfl_data.head()

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,desc,PlayAttempted,Yards.Gained,...,Timeout_Indicator,Timeout_Team,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,2009-09-10,2009091000,1,1,15,0,0,R.Bironas kicks 67 yards from TEN 30 to PIT 3....,1,39,...,0,None,3,3,3,3,3,0.0,0.0,2009
1,2009-09-10,2009091000,1,1,15,10,5,(14:53) B.Roethlisberger pass short left to H....,1,5,...,0,None,3,3,3,3,3,0.0,0.0,2009
2,2009-09-10,2009091000,1,1,15,5,2,(14:16) W.Parker right end to PIT 44 for -3 ya...,1,-3,...,0,None,3,3,3,3,3,0.0,0.0,2009
3,2009-09-10,2009091000,1,1,14,8,2,(13:35) (Shotgun) B.Roethlisberger pass incomp...,1,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
4,2009-09-10,2009091000,1,1,14,8,2,(13:27) (Punt formation) D.Sepulveda punts 54 ...,1,0,...,0,None,3,3,3,3,3,0.0,0.0,2009

In [163]:
#Examine the shape of new data set
nfl_data.shape

(407688, 42)

In [165]:
nfl_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407688 entries, 0 to 407687
Data columns (total 42 columns):
Date                           407688 non-null object
GameID                         407688 non-null int64
Drive                          407688 non-null int64
qtr                            407688 non-null int64
TimeUnder                      407688 non-null int64
ydstogo                        407688 non-null int64
ydsnet                         407688 non-null int64
desc                           407686 non-null object
PlayAttempted                  407688 non-null int64
Yards.Gained                   407688 non-null int64
sp                             407688 non-null int64
Touchdown                      407688 non-null int64
Safety                         407688 non-null int64
Onsidekick                     407688 non-null int64
PlayType                       407688 non-null object
Passer_ID                      407688 non-null object
PassAttempt                    407688 non-null int64
AirYards                       407688 non-null int64
YardsAfterCatch                407688 non-null int64
QBHit                          407688 non-null int64
InterceptionThrown             407688 non-null int64
Rusher_ID                      407688 non-null object
RushAttempt                    407688 non-null int64
Receiver_ID                    407688 non-null object
Reception                      407688 non-null int64
Fumble                         407688 non-null int64
Sack                           407688 non-null int64
Challenge.Replay               407688 non-null int64
Accepted.Penalty               407688 non-null int64
Penalty.Yards                  407688 non-null int64
HomeTeam                       407688 non-null object
AwayTeam                       407688 non-null object
Timeout_Indicator              407688 non-null int64
Timeout_Team                   407688 non-null object
posteam_timeouts_pre           407688 non-null int64
HomeTimeouts_Remaining_Pre     407688 non-null int64
AwayTimeouts_Remaining_Pre     407688 non-null int64
HomeTimeouts_Remaining_Post    407688 non-null int64
AwayTimeouts_Remaining_Post    407688 non-null int64
ExPoint_Prob                   407688 non-null float64
TwoPoint_Prob                  407688 non-null float64
Season                         407688 non-null int64
dtypes: float64(2), int64(31), object(9)
memory usage: 130.6+ MB

In [167]:
#Examine how many missing values new dataset have
nfl_data.isnull().sum().max()

2

In [170]:
# 'value_counts' does not include missing values by default
nfl_data['desc'].value_counts().head(10)

Two-Minute Warning                                                 3739
END GAME                                                           1913
END QUARTER 3                                                      1869
END QUARTER 1                                                      1570
END QUARTER 2                                                      1287
G.Gano kicks 65 yards from CAR 35 to end zone, Touchback.           320
M.Bosher kicks 65 yards from ATL 35 to end zone, Touchback.         293
S.Gostkowski kicks 65 yards from NE 35 to end zone, Touchback.      284
J.Tucker kicks 65 yards from BAL 35 to end zone, Touchback.         258
M.Crosby extra point is GOOD, Center-B.Goode, Holder-T.Masthay.     255
Name: desc, dtype: int64

In [178]:
# explicitly include missing values
nfl_data['desc'].value_counts(dropna=False).head()

Two-Minute Warning    3739
END GAME              1913
END QUARTER 3         1869
END QUARTER 1         1570
END QUARTER 2         1287
Name: desc, dtype: int64

In [ ]:
# fill in missing values with a specified value
#nfl_data['desc'].fillna(value='VARIOUS', inplace=True)

In [179]:
# Now we will remove all columns which have any missing values
nfl_data_1 = nfl_data.dropna(how='any',axis=1)
nfl_data_1.head()

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,...,Timeout_Indicator,Timeout_Team,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,2009-09-10,2009091000,1,1,15,0,0,1,39,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
1,2009-09-10,2009091000,1,1,15,10,5,1,5,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
2,2009-09-10,2009091000,1,1,15,5,2,1,-3,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
3,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
4,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009

In [180]:
#Examine the shape of new data set again
nfl_data_1.shape

(407688, 41)

In [181]:
nfl_data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407688 entries, 0 to 407687
Data columns (total 41 columns):
Date                           407688 non-null object
GameID                         407688 non-null int64
Drive                          407688 non-null int64
qtr                            407688 non-null int64
TimeUnder                      407688 non-null int64
ydstogo                        407688 non-null int64
ydsnet                         407688 non-null int64
PlayAttempted                  407688 non-null int64
Yards.Gained                   407688 non-null int64
sp                             407688 non-null int64
Touchdown                      407688 non-null int64
Safety                         407688 non-null int64
Onsidekick                     407688 non-null int64
PlayType                       407688 non-null object
Passer_ID                      407688 non-null object
PassAttempt                    407688 non-null int64
AirYards                       407688 non-null int64
YardsAfterCatch                407688 non-null int64
QBHit                          407688 non-null int64
InterceptionThrown             407688 non-null int64
Rusher_ID                      407688 non-null object
RushAttempt                    407688 non-null int64
Receiver_ID                    407688 non-null object
Reception                      407688 non-null int64
Fumble                         407688 non-null int64
Sack                           407688 non-null int64
Challenge.Replay               407688 non-null int64
Accepted.Penalty               407688 non-null int64
Penalty.Yards                  407688 non-null int64
HomeTeam                       407688 non-null object
AwayTeam                       407688 non-null object
Timeout_Indicator              407688 non-null int64
Timeout_Team                   407688 non-null object
posteam_timeouts_pre           407688 non-null int64
HomeTimeouts_Remaining_Pre     407688 non-null int64
AwayTimeouts_Remaining_Pre     407688 non-null int64
HomeTimeouts_Remaining_Post    407688 non-null int64
AwayTimeouts_Remaining_Post    407688 non-null int64
ExPoint_Prob                   407688 non-null float64
TwoPoint_Prob                  407688 non-null float64
Season                         407688 non-null int64
dtypes: float64(2), int64(31), object(8)
memory usage: 127.5+ MB

In [157]:
# Again Examine how many missing values new dataset have
nfl_data_1.isnull().sum().max()

0